### ISSUE TITLE
HTTP方法

### ISSUE THREAD

**Issue by linxuyalun** [Gusabary/Winter-Vacation#1]
在你的[learning notes 1.16_HTML](https://github.com/Gusabary/Winter-Vacation/blob/master/Week%201/learning%20notes%201.16_HTML.md)，你在记录表单相关知识的时候写到：
> method 属性定义了发送数据的HTTP方法(它可以是“get”或“post”).

那么，什么是**HTTP 方法**？它主要的作用是什么？它都有哪些？各自的作用是什么？

**Comment by Gusabary** [comment]
> 在你的[learning notes 1.16_HTML](https://github.com/Gusabary/Winter-Vacation/blob/master/Week%201/learning%20notes%201.16_HTML.md)，你在记录表单相关知识的时候写到：
> 
> > method 属性定义了发送数据的HTTP方法(它可以是“get”或“post”).
> 
> 那么，什么是**HTTP 方法**？它主要的作用是什么？它都有哪些？各自的作用是什么？

建立客户端与服务器之间联系的方法？（可能
保证客户端与服务器之间的通信。
主要的有 `Get` 和 `Post` ，还有其他的一些。
`Get` 是浏览器发送空的主体，将数据追加在 URL 之后。
`Post` 是将数据放在请求主体内部。
//大概是这样

**Comment by linxuyalun** [comment]
[What is CRUD?](https://www.codecademy.com/articles/what-is-crud)
**Further Reading**:
[What is REST?](https://www.codecademy.com/articles/what-is-rest)

**Comment by Gusabary** [comment]
[Here](https://github.com/Gusabary/Winter-Vacation/blob/master/Week%202/HTTP%20verbs.md) is my comprehension about CRUD and REST.
