### ISSUE TITLE
1.20笔记相关

### ISSUE THREAD

**Issue by linxuyalun** [Gusabary/Winter-Vacation#2]
1. 你已经了解了object相关的内容，object作为js的其中一个内建类型，其他几种内建类型是什么？数组属于哪一种内建类型？
2. 你已经了解了严格等于，严格等于和不严格等于的差别是什么？
3. 在你的笔记中，你记录了关于`字符串与数字类型的互换`的内容，这称为强制转换，但是例子中只有显式强制转换，了解隐式强制转换
4. 在js中，一个对象object，它可以有一些属于自己的属性和方法，但是显然字符串也有自己的属性和方法，比如`s.length`是字符串的一个属性，`s.toLowerCase()`是字符串的一个方法。查找相关资料试解释内建类型拥有属性和方法的原因。

**Comment by Gusabary** [comment]
1. 内建类型：string, number, boolean, object, function, null, undefined.
    数组属于 object 类型。
2. 不严格等于允许数据类型不同，而严格等于不允许。
3. [隐式强制转换](http://www.cnblogs.com/mizzle/archive/2011/08/12/2135885.html)
    `+` 会将操作数向 `string` 类型转换。
    `-`, `*`, `/`, `%` 会将操作数向 `number` 类型转换。
4.  ..
