### ISSUE TITLE
1.23笔记相关

### ISSUE THREAD

**Issue by linxuyalun** [Gusabary/Winter-Vacation#3]
> JavaScript 的逻辑与 &&，它可以方便地条件渲染一个元素：
> ```react
> return (
>   <div>
>    <h1>Hello!</h1>
>     {unreadMessages.length > 0 &&
>      <h2>
>         You have {unreadMessages.length} unread messages.
>       </h2>
>    }
>   </div>
> );
>```
解释一下这种逻辑与操作能work背后的逻辑。

**Comment by Gusabary** [comment]
对于表达式 `conditionA && conditionB`, 如果 `conditionA` 为假，则不会再对 `conditionB` 进行判断。
所以如果 `unreadMessages.length > 0` 为假，则不会渲染 `<h2>` 元素，反之则会。

**Comment by linxuyalun** [comment]
在Js中，`&&`和`||`产生的结果并不是一些语言（比如C，go）通常意义上的的`true`或`false`，实际上，它产生的值总是为表达式中的一个值（类似的还有Python和Ruby）：
```js
const a = 1
const b = 'b'
const c = null

a || b		// 1
a && b		// 'b'

c || b		// 'b'
c && b		// null
```
**Further Reading**：
[Falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy)
